"""add core domain models

Revision ID: 320eb68d0524
Revises: b466dcebf02c
Create Date: 2026-08-18 11:42:48.067704

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "320eb68d0524"
down_revision: str | Sequence[str] | None = "b466dcebf02c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "agent_actions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("action_type", sa.String(length=255), nullable=False),
        sa.Column("tool_name", sa.String(length=255), nullable=True),
        sa.Column("input_data", sa.JSON(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "APPROVED",
                "REJECTED",
                "COMPLETED",
                "FAILED",
                name="agent_action_status",
            ),
            nullable=False,
        ),
        sa.Column("requires_approval", sa.Boolean(), nullable=False),
        sa.Column("approval_id", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agent_actions_user_id"), "agent_actions", ["user_id"], unique=False
    )
    op.create_table(
        "people",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("relationship_label", sa.String(length=255), nullable=True),
        sa.Column("usual_response_days", sa.Float(), nullable=True),
        sa.Column("last_interaction", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_people_user_id"), "people", ["user_id"], unique=False)
    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("goal", sa.String(length=2000), nullable=True),
        sa.Column("deadline", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "COMPLETED", "ARCHIVED", name="project_status"),
            nullable=False,
        ),
        sa.Column("next_action", sa.String(length=1000), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_projects_user_id"), "projects", ["user_id"], unique=False)
    op.create_table(
        "commitments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("person_id", sa.Integer(), nullable=True),
        sa.Column("description", sa.String(length=2000), nullable=False),
        sa.Column(
            "owner", sa.Enum("USER", "OTHER", name="commitment_owner"), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum("OPEN", "COMPLETED", "CANCELLED", name="commitment_status"),
            nullable=False,
        ),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_message_id", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["people.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_commitments_person_id"), "commitments", ["person_id"], unique=False
    )
    op.create_index(
        op.f("ix_commitments_user_id"), "commitments", ["user_id"], unique=False
    )
    op.add_column(
        "tasks",
        sa.Column("user_id", sa.Integer(), nullable=True),
    )
    connection = op.get_bind()

    temporary_user_id = connection.execute(
        sa.text(
            """
            INSERT INTO users (email, name)
            VALUES (:email, :name)
            RETURNING id
            """
        ),
        {
            "email": "local-user@ai-life-manager.invalid",
            "name": "Local User",
        },
    ).scalar_one()

    connection.execute(
        sa.text(
            """
            UPDATE tasks
            SET user_id = :user_id
            WHERE user_id IS NULL
            """
        ),
        {"user_id": temporary_user_id},
    )

    op.alter_column(
        "tasks",
        "user_id",
        nullable=False,
    )
    op.add_column("tasks", sa.Column("project_id", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_tasks_project_id"), "tasks", ["project_id"], unique=False)
    op.create_index(op.f("ix_tasks_user_id"), "tasks", ["user_id"], unique=False)
    op.create_foreign_key(
        "fk_tasks_project_id_projects", "tasks", "projects", ["project_id"], ["id"]
    )
    op.create_foreign_key(
        "fk_tasks_user_id_users", "tasks", "users", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_tasks_project_id_projects", "tasks", type_="foreignkey")
    op.drop_constraint("fk_tasks_user_id_users", "tasks", type_="foreignkey")
    op.drop_index(op.f("ix_tasks_user_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_project_id"), table_name="tasks")
    op.drop_column("tasks", "project_id")
    op.drop_column("tasks", "user_id")
    op.drop_index(op.f("ix_commitments_user_id"), table_name="commitments")
    op.drop_index(op.f("ix_commitments_person_id"), table_name="commitments")
    op.drop_table("commitments")
    op.drop_index(op.f("ix_projects_user_id"), table_name="projects")
    op.drop_table("projects")
    op.drop_index(op.f("ix_people_user_id"), table_name="people")
    op.drop_table("people")
    op.drop_index(op.f("ix_agent_actions_user_id"), table_name="agent_actions")
    op.drop_table("agent_actions")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    sa.Enum(
        "PENDING",
        "APPROVED",
        "REJECTED",
        "COMPLETED",
        "FAILED",
        name="agent_action_status",
    ).drop(op.get_bind(), checkfirst=True)

    sa.Enum(
        "OPEN",
        "COMPLETED",
        "CANCELLED",
        name="commitment_status",
    ).drop(op.get_bind(), checkfirst=True)

    sa.Enum(
        "USER",
        "OTHER",
        name="commitment_owner",
    ).drop(op.get_bind(), checkfirst=True)

    sa.Enum(
        "ACTIVE",
        "COMPLETED",
        "ARCHIVED",
        name="project_status",
    ).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
